# Generated by Django 4.2.1 on 2023-07-18 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pic1',
            field=models.ImageField(blank=True, null=True, upload_to='upload/product'),
        ),
    ]
