# Generated by Django 4.2.1 on 2023-08-06 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0007_contact_newsletter'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Newsletter',
            new_name='Newslatter',
        ),
    ]
