# Generated by Django 4.2.1 on 2023-08-07 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0008_rename_newsletter_newslatter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('pic', models.ImageField(upload_to='uploads/testimonials')),
            ],
        ),
    ]
