# Generated by Django 4.2.1 on 2023-08-08 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0009_testimonial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='otp',
            field=models.IntegerField(blank=None, default=None, null=True),
        ),
    ]
